.TH <WIFIDMON>
.SH SYNOPSIS
.B Wireless daemon
.SH DESCRIPTION
.B DMON is a wireless networking daemon, automates the steps involved in connecting to networks. To set up first add the compiled program to a start up script which is contained within the log in session and fill out the configuration file. Instructions on how to fill out the configuration file are specified in the file itself.
.B On the first start up wifidmon creates a config file in /etc/DMON/.
.SH AUTHOR
.B WIFIDMON was written by Ceysun sucu for the OpenBSD project.
